name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Start SUT
        run: java -jar ./artifacts/app-replan-delivery.jar &

      - name: Wait for SUT to be available
        run: |
          echo "Waiting for server to be available..."
          for i in {1..30}; do
            nc -z localhost 9999 && echo "Server is available" && break
            echo "Waiting..."
            sleep 1
          done
        # Время ожидания увеличено до 30 секунд, чтобы обеспечить запуск сервера

      - name: Build with Gradle and run tests
        run: ./gradlew test --info -Dselenide.headless=true