name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkoutv2
      - name: Set up JDK
        uses: actions/setup-java@v2
      :
      java-version: '11'
      distribution: 'ad'
      - name: Grant execute permission for gradlew
  run: chmod +x gradlew
         - name: SUT
         run: java -jar ./artifacts/app-replan-delivery.jar &
         - name: Wait for SUT to start
           run: sleep 10
         - name: Build with Grad
           run: ./gradlew test --info -Dide.headless=true